name: flutter_homework
description: Flutter Exercises

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: any
  audioplayers: ^0.17.0
  cupertino_icons: ^1.0.0
  built_value: ^7.1.0
  built_collection: ^4.3.2
  http: any
  redux: ^4.0.0+3
  flutter_redux: ^0.7.0
  freezed_annotation: ^0.12.0
  rxdart: any
  redux_epics: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.2.0
  build_runner: '>=1.0.0 <2.0.0'
  built_value_generator: ^7.1.0
  freezed: any

flutter:

  uses-material-design: true
  assets:
    - assets/images/Math.png
  fonts:
    - family: NerkoOne
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf
